name: Q1
max_score: 110
out_limit: 11

languages:
  c:
    time: 1000
    memory: 50
    rules:
      - simple
  cpp:
    time: 1100
    memory: 55
    #rules:
      #- non-existing-rule
  java:
    time: 3000
    memory: 256
    rules:
     - empty

